Repository balpyo-myeotbun/balpyoMyeotbun-android, pull requests merged in 2024-08, with the labels that each got.

#92 [#76] 대본 생성 화면 버튼 스타일 변경
  app/src/main/java/com/project/balpyo/Script/Adapter/SubTopicCheckAdapter.kt
  app/src/main/java/com/project/balpyo/Script/ScriptCheckFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptResultFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptSubtopicFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptTimeFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptTitleFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptTopicFragment.kt
  app/src/main/java/com/project/balpyo/TimeCalculator/TimeCalculatorResultFragment.kt
  app/src/main/res/layout/fragment_script_check.xml
  app/src/main/res/layout/fragment_script_result.xml
  app/src/main/res/layout/fragment_script_subtopic.xml
  app/src/main/res/layout/fragment_script_title.xml
  app/src/main/res/layout/fragment_script_topic.xml
  app/src/main/res/layout/fragment_time_calculator_result.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: Feat

#94 Style/#85
  app/src/main/java/com/project/balpyo/BottomSheetData/BottomSheetItem.kt
  app/src/main/java/com/project/balpyo/FlowController/FlowControllerEditScriptFragment.kt
  app/src/main/java/com/project/balpyo/FlowController/FlowControllerTitleFragment.kt
  app/src/main/java/com/project/balpyo/Home/HomeFragment.kt
  app/src/main/java/com/project/balpyo/Home/StorageFragment.kt
  app/src/main/java/com/project/balpyo/LoadingFragment.kt
  app/src/main/java/com/project/balpyo/LoginFragment.kt
  app/src/main/java/com/project/balpyo/MainActivity.kt
  app/src/main/java/com/project/balpyo/MyPage/MyPageFragment.kt
  app/src/main/java/com/project/balpyo/Sign/Adapter/SpinnerAdapter.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpEmailFragment.kt
  app/src/main/java/com/project/balpyo/Sign/ViewModel/SignViewModel.kt
  app/src/main/java/com/project/balpyo/SplashFragment.kt
  app/src/main/java/com/project/balpyo/Storage/Adapter/SearchAdapter.kt
  app/src/main/java/com/project/balpyo/Storage/Adapter/SearchHistoryAdapter.kt
  app/src/main/java/com/project/balpyo/Storage/Adapter/StorageAdapter.kt
  app/src/main/java/com/project/balpyo/Storage/FilterBottomSheet/FilterBottomSheetFragment.kt
  app/src/main/java/com/project/balpyo/Storage/LoadScriptBottomSheet/Adapter/LoadScriptBottomSheetAdapter.kt
  app/src/main/java/com/project/balpyo/Storage/LoadScriptBottomSheet/Data/BottomSheetData.kt
  app/src/main/java/com/project/balpyo/Storage/LoadScriptBottomSheet/LoadScriptBottomSheetFragment.kt
  app/src/main/java/com/project/balpyo/Storage/SearchHistoryManager.kt
  app/src/main/java/com/project/balpyo/Storage/StorageEditDeleteFragment.kt
  app/src/main/java/com/project/balpyo/Storage/StorageFragment.kt
  app/src/main/java/com/project/balpyo/Storage/ViewModel/StorageViewModel.kt
  app/src/main/java/com/project/balpyo/TimeCalculator/TimeCalculatorScriptFragment.kt
  app/src/main/java/com/project/balpyo/api/response/StorageListResponse.kt
  app/src/main/res/anim/rotate.xml
  app/src/main/res/drawable/animation_loading.xml
  app/src/main/res/drawable/background_add_note.xml
  app/src/main/res/drawable/background_filter_bottomsheet.xml
  app/src/main/res/drawable/background_search.xml
  app/src/main/res/drawable/background_search_edit.xml
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/drawable/ic_plus_note.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_delete.xml
  app/src/main/res/drawable/spinner_shape_dropdown_background.xml
  app/src/main/res/layout/fragment_filter_bottom_sheet.xml
  app/src/main/res/layout/fragment_loading.xml
  app/src/main/res/layout/fragment_sign_up_email.xml
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/layout/fragment_storage_edit_delete.xml
  app/src/main/res/layout/item_search_history.xml
  app/src/main/res/layout/spinner_item_background.xml
  app/src/main/res/layout/spinner_item_background_null.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: Style, Feat

#96 Feat/#95
  app/src/main/java/com/project/balpyo/FlowController/FlowControllerEditScriptFragment.kt
  app/src/main/java/com/project/balpyo/Home/HomeFragment.kt
  app/src/main/java/com/project/balpyo/LoadingFragment.kt
  app/src/main/java/com/project/balpyo/LoginFragment.kt
  app/src/main/java/com/project/balpyo/MainActivity.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpCertificationFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpCompleteFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpPasswordFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpTermsFragment.kt
  app/src/main/java/com/project/balpyo/TimeCalculator/TimeCalculatorScriptFragment.kt
  app/src/main/res/drawable/background_bottom_nav.xml
  app/src/main/res/drawable/background_kakao_login.xml
  app/src/main/res/drawable/background_login_email.xml
  app/src/main/res/drawable/ic_bottom_navigation_bar_home_select_svg.xml
  app/src/main/res/drawable/ic_bottom_navigation_bar_home_unselect_svg.xml
  app/src/main/res/drawable/ic_bottom_navigation_bar_profile_select_svg.xml
  app/src/main/res/drawable/ic_bottom_navigation_bar_profile_unselect_svg.xml
  app/src/main/res/drawable/ic_bottom_navigation_bar_storage_select_svg.xml
  app/src/main/res/drawable/ic_bottom_navigation_bar_storage_unselect_svg.xml
  app/src/main/res/drawable/ic_email.xml
  app/src/main/res/drawable/ic_generate_script.xml
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/ic_login.xml
  app/src/main/res/drawable/selector_bottom_nav_home.xml
  app/src/main/res/drawable/selector_bottom_nav_profile.xml
  app/src/main/res/drawable/selector_bottom_nav_storage.xml
  app/src/main/res/drawable/selector_bottom_nav_text.xml
  app/src/main/res/font/apple_sd_gothic_neo_sb.ttf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_flow_controller_edit_script.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: Style, Feat

#97 [#96] 대본 생성 FCM 푸시 알림 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/balpyo/FirebaseService.kt
  app/src/main/java/com/project/balpyo/Home/HomeFragment.kt
  app/src/main/java/com/project/balpyo/MainActivity.kt
  app/src/main/java/com/project/balpyo/NotificationActivity.kt
  app/src/main/java/com/project/balpyo/Script/ScriptCheckFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptCompleteFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptResultFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptSubtopicFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptTimeFragment.kt
  app/src/main/java/com/project/balpyo/Script/ViewModel/GenerateScriptViewModel.kt
  app/src/main/java/com/project/balpyo/Utils/MyApplication.kt
  app/src/main/java/com/project/balpyo/Utils/PreferenceUtil.kt
  app/src/main/java/com/project/balpyo/api/ApiService.kt
  app/src/main/java/com/project/balpyo/api/request/GenerateScriptRequest.kt
  app/src/main/java/com/project/balpyo/api/request/ManageScriptRequest.kt
  app/src/main/java/com/project/balpyo/api/response/ManageScriptResponse.kt
  app/src/main/res/drawable/animation_loading_script_generating.xml
  app/src/main/res/drawable/background_loading.xml
  app/src/main/res/drawable/loading1.xml
  app/src/main/res/drawable/loading2.xml
  app/src/main/res/drawable/loading3.xml
  app/src/main/res/drawable/loading4.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/dialog_script_time.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_script_check.xml
  app/src/main/res/layout/fragment_script_complete.xml
  app/src/main/res/layout/fragment_script_subtopic.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/raw/script_check.gif
  build.gradle.kts
  gradle/libs.versions.toml
Labels: Feat

#100 [#99] 온보딩 화면 UI
  app/build.gradle.kts
  app/src/main/java/com/project/balpyo/MainActivity.kt
  app/src/main/java/com/project/balpyo/Onboarding/Onboarding1Fragment.kt
  app/src/main/java/com/project/balpyo/Onboarding/Onboarding2Fragment.kt
  app/src/main/java/com/project/balpyo/Onboarding/Onboarding3Fragment.kt
  app/src/main/java/com/project/balpyo/Onboarding/Onboarding4Fragment.kt
  app/src/main/java/com/project/balpyo/Onboarding/Onboarding5Fragment.kt
  app/src/main/java/com/project/balpyo/SplashFragment.kt
  app/src/main/res/drawable/ic_onboarding1.xml
  app/src/main/res/layout/fragment_onboarding1.xml
  app/src/main/res/layout/fragment_onboarding2.xml
  app/src/main/res/layout/fragment_onboarding3.xml
  app/src/main/res/layout/fragment_onboarding4.xml
  app/src/main/res/layout/fragment_onboarding5.xml
  app/src/main/res/layout/fragment_splash.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/raw/onboarding_flow.gif
  app/src/main/res/raw/onboarding_script.gif
  app/src/main/res/raw/onboarding_timecalculator.gif
  app/src/main/res/raw/splash_json.json
  app/src/main/res/values/strings.xml
Labels: Style, Feat

#102 [#98] Feat: 앱링크 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/balpyo/Sign/SignUpCertificationFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpPasswordFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpTermsFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: Feat

#104 Fix/#103
  app/src/main/java/com/project/balpyo/FlowController/AddTime/FlowControllerAddTimeFragment.kt
  app/src/main/java/com/project/balpyo/FlowController/FlowControllerPreviewFragment.kt
  app/src/main/java/com/project/balpyo/FlowController/FlowControllerResultFragment.kt
  app/src/main/java/com/project/balpyo/FlowController/FlowControllerTitleFragment.kt
  app/src/main/java/com/project/balpyo/Home/HomeFragment.kt
  app/src/main/java/com/project/balpyo/LoginFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptCheckFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptResultFragment.kt
  app/src/main/java/com/project/balpyo/Script/ViewModel/GenerateScriptViewModel.kt
  app/src/main/java/com/project/balpyo/Sign/EmailLoginFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpCertificationFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpCompleteFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpEmailFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpPasswordFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpTermsFragment.kt
  app/src/main/java/com/project/balpyo/Sign/ViewModel/SignViewModel.kt
  app/src/main/java/com/project/balpyo/SplashFragment.kt
  app/src/main/java/com/project/balpyo/Storage/Adapter/SearchAdapter.kt
  app/src/main/java/com/project/balpyo/Storage/Adapter/StorageAdapter.kt
  app/src/main/java/com/project/balpyo/Storage/StorageEditDeleteFragment.kt
  app/src/main/java/com/project/balpyo/Storage/StorageFragment.kt
  app/src/main/java/com/project/balpyo/Storage/ViewModel/StorageViewModel.kt
  app/src/main/java/com/project/balpyo/TimeCalculator/TimeCalculatorResultFragment.kt
  app/src/main/java/com/project/balpyo/TimeCalculator/TimeCalculatorSpeedFragment.kt
  app/src/main/java/com/project/balpyo/Utils/PreferenceHelper.kt
  app/src/main/java/com/project/balpyo/api/ApiService.kt
  app/src/main/java/com/project/balpyo/api/request/SignInRequest.kt
  app/src/main/java/com/project/balpyo/api/response/StorageDetailResponse.kt
  app/src/main/java/com/project/balpyo/api/response/StorageListResponse.kt
  app/src/main/res/drawable/ic_edit_flowcontroller.xml
  app/src/main/res/drawable/ic_email_login.xml
  app/src/main/res/drawable/ic_storage_flowcontroller.xml
  app/src/main/res/drawable/selector_emali_login_eddittext.xml
  app/src/main/res/layout/fragment_email_login.xml
  app/src/main/res/layout/fragment_flow_controller_result.xml
  app/src/main/res/layout/fragment_sign_up_certification.xml
  app/src/main/res/layout/fragment_sign_up_email.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: Fix, Feat

#105 Fix/#103
  app/src/main/java/com/project/balpyo/Sign/SignUpCompleteFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpEmailFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpPasswordFragment.kt
  app/src/main/java/com/project/balpyo/Sign/SignUpTermsFragment.kt
  app/src/main/java/com/project/balpyo/Sign/ViewModel/SignViewModel.kt
  app/src/main/res/layout/fragment_email_login.xml
Labels: Fix

#106 [#101] 노트 작성 화면 구성 및 기능 구현
  app/src/main/ic_icon-playstore.png
  app/src/main/java/com/project/balpyo/Storage/NoteBottomSheet/NoteBottomSheetFragment.kt
  app/src/main/java/com/project/balpyo/Storage/NoteFragment.kt
  app/src/main/res/drawable/ic_icon_foreground.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/ic_tooltip.xml
  app/src/main/res/layout/fragment_note.xml
  app/src/main/res/layout/fragment_note_bottom_sheet.xml
  app/src/main/res/mipmap-hdpi/ic_icon.webp
  app/src/main/res/mipmap-hdpi/ic_icon_round.webp
  app/src/main/res/mipmap-mdpi/ic_icon.webp
  app/src/main/res/mipmap-mdpi/ic_icon_round.webp
  app/src/main/res/mipmap-xhdpi/ic_icon.webp
  app/src/main/res/mipmap-xhdpi/ic_icon_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_icon.webp
  app/src/main/res/mipmap-xxhdpi/ic_icon_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_icon.webp
  app/src/main/res/mipmap-xxxhdpi/ic_icon_round.webp
  app/src/main/res/navigation/nav_graph.xml
Labels: Style, Feat

#108 [#107] Feat: 닉네임 표시 및 레이아웃 수정
  app/src/main/java/com/project/balpyo/Home/HomeFragment.kt
  app/src/main/java/com/project/balpyo/MyPage/MyPageAccountFragment.kt
  app/src/main/java/com/project/balpyo/MyPage/MyPageFragment.kt
  app/src/main/java/com/project/balpyo/MyPage/MyPageProfileFragment.kt
  app/src/main/java/com/project/balpyo/Sign/ViewModel/SignViewModel.kt
  app/src/main/java/com/project/balpyo/Storage/StorageFragment.kt
  app/src/main/java/com/project/balpyo/Utils/PreferenceHelper.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_storage.xml
Labels: Style, Feat

#110 [#93] 대본 생성 FCM 푸시 알림 설정 및 비동기 처리 기능 구현
  app/build.gradle.kts
  app/src/main/java/com/project/balpyo/FirebaseService.kt
  app/src/main/java/com/project/balpyo/FlowController/FlowControllerEditScriptFragment.kt
  app/src/main/java/com/project/balpyo/Home/HomeFragment.kt
  app/src/main/java/com/project/balpyo/MainActivity.kt
  app/src/main/java/com/project/balpyo/NotificationActivity.kt
  app/src/main/java/com/project/balpyo/Onboarding/Onboarding5Fragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptCheckFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptResultFragment.kt
  app/src/main/java/com/project/balpyo/Script/ViewModel/GenerateScriptViewModel.kt
  app/src/main/java/com/project/balpyo/Script/ViewModel/ScriptDetailViewModel.kt
  app/src/main/java/com/project/balpyo/SplashFragment.kt
  app/src/main/java/com/project/balpyo/Storage/NoteFragment.kt
  app/src/main/java/com/project/balpyo/Storage/StorageFragment.kt
  app/src/main/java/com/project/balpyo/Storage/ViewModel/StorageViewModel.kt
  app/src/main/java/com/project/balpyo/TimeCalculator/TimeCalculatorResultFragment.kt
  app/src/main/java/com/project/balpyo/Utils/MyApplication.kt
  app/src/main/java/com/project/balpyo/Utils/PreferenceUtil.kt
  app/src/main/java/com/project/balpyo/api/request/GenerateScriptRequest.kt
  app/src/main/java/com/project/balpyo/api/request/ManageScriptRequest.kt
  app/src/main/java/com/project/balpyo/api/request/StoreScriptRequest.kt
  app/src/main/java/com/project/balpyo/api/response/StorageDetailResponse.kt
  app/src/main/res/drawable/background_tooltip.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_script_result.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: Style, Feat

#113 [#109] Style: 보관함 툴바 및 레이아웃 모드 수정
  app/src/main/java/com/project/balpyo/Storage/StorageFragment.kt
Labels: Fix

#114 Feat/#112
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/balpyo/LoginFragment.kt
  app/src/main/java/com/project/balpyo/Utils/GlobalApplication.kt
  settings.gradle.kts
Labels: Feat

#116 [#115] Fix: UID 로그인 삭제
  app/src/main/java/com/project/balpyo/LoginFragment.kt
  app/src/main/res/layout/fragment_login.xml
Labels: Fix

#118 Fix/#117
  app/src/main/java/com/project/balpyo/FlowController/FlowControllerResultFragment.kt
  app/src/main/java/com/project/balpyo/Home/BannerFragment.kt
  app/src/main/java/com/project/balpyo/Home/HomeFragment.kt
  app/src/main/java/com/project/balpyo/Storage/StorageEditFlowControllerScriptFragment.kt
  app/src/main/res/drawable/background_banner.xml
  app/src/main/res/drawable/ic_kebab_menu.xml
  app/src/main/res/layout/fragment_banner.xml
  app/src/main/res/layout/fragment_flow_controller_result.xml
  app/src/main/res/layout/fragment_sign_up_certification.xml
  app/src/main/res/layout/fragment_storage_edit_flow_controller_script.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: Fix, Style

#120 [#119] Fix: 네비게이션 수정 및 api 엔드포인트 수정
  app/src/main/java/com/project/balpyo/FlowController/FlowControllerResultFragment.kt
  app/src/main/java/com/project/balpyo/api/ApiService.kt
Labels: Fix

#121 [#119] Fix: 버튼 활성화
  app/src/main/java/com/project/balpyo/FlowController/FlowControllerEditScriptFragment.kt
Labels: Fix

#122 [#111] 보관함 수정 기능 구현 및 권한 설정 기능 수정
  app/src/main/java/com/project/balpyo/Script/ScriptCompleteFragment.kt
  app/src/main/java/com/project/balpyo/Storage/StorageEditBottomSheet/StorageEditBottomSheetFragment.kt
  app/src/main/java/com/project/balpyo/Storage/StorageEditDeleteFragment.kt
  app/src/main/res/layout/fragment_storage_edit_delete.xml
Labels: Fix, Feat
