Repository balpyo-myeotbun/balpyoMyeotbun-android, pull requests merged in 2024-05, with the labels that each got.

#52 [#51] 단어당 발표 시간 계산기(관리기) 시간 초과 계산 기능 구현
  app/src/main/java/com/project/balpyo/TimeCalculator/TimeCalculatorResultFragment.kt
  app/src/main/java/com/project/balpyo/TimeCalculator/TimeCalculatorSpeedFragment.kt
  app/src/main/res/layout/fragment_time_calculator_result.xml
Labels: Feat

#55 [#53] 화면 디테일 수정
  app/src/main/AndroidManifest.xml
  app/src/main/ic_icon-playstore.png
  app/src/main/java/com/project/balpyo/Script/ScriptResultFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptTimeFragment.kt
  app/src/main/java/com/project/balpyo/TimeCalculator/TimeCalculatorTimeFragment.kt
  app/src/main/res/drawable/ic_icon_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_icon.xml
  app/src/main/res/mipmap-anydpi-v26/ic_icon_round.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_icon.webp
  app/src/main/res/mipmap-hdpi/ic_icon_round.webp
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_icon.webp
  app/src/main/res/mipmap-mdpi/ic_icon_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_icon.webp
  app/src/main/res/mipmap-xhdpi/ic_icon_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_icon.webp
  app/src/main/res/mipmap-xxhdpi/ic_icon_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_icon.webp
  app/src/main/res/mipmap-xxxhdpi/ic_icon_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/ic_icon_background.xml
Labels: Fix

#56 [#50] 비동기 수정
  app/src/main/java/com/project/balpyo/FlowController/FlowControllerResultFragment.kt
  app/src/main/java/com/project/balpyo/FlowController/ScriptSync/ScriptSynchronizer.kt
  app/src/main/java/com/project/balpyo/Home/HomeFragment.kt
  app/src/main/java/com/project/balpyo/MainActivity.kt
  app/src/main/java/com/project/balpyo/Script/ScriptResultFragment.kt
  app/src/main/java/com/project/balpyo/Script/ScriptTimeFragment.kt
  app/src/main/java/com/project/balpyo/Script/ViewModel/GenerateScriptViewModel.kt
Labels: Fix, Feat, Refactor
